import { Product } from './product.model';
import { UserModel } from './user.model';
// Generated by https://quicktype.io

export interface CartResponse {
  status: boolean;
  guardado: Cart;
  carrito?: Cart;
}

export interface Cart {
  totalPrice: number;
  _id: string;
  items: Item[];
  totalItems: number;
  user: UserModel;
}

export interface Item {
  quantity: number;
  product: Product;
}
