export interface ProductResponse {
  status: boolean;
  product: Product[] | Product;
}

export class Product {
  id: string;
  name: string;
  // tslint:disable-next-line: variable-name
  desc_short: string;
  // tslint:disable-next-line: variable-name
  desc_long: string;
  price: number;
  category: string;
  img: string;
  stock: number;

  constructor(obj: any) {
    this.id = obj.id || obj._id;
    this.name = obj.name;
    this.desc_short = obj.descShort || obj.desc_short;
    this.desc_long = obj.descLong || obj.desc_long;
    this.price = obj.price;
    this.category = obj.category;
    this.img = obj.img;
    this.stock = obj.stock;
  }
}

// Generated by https://quicktype.io

export interface Category {
  _id: string;
  name: string;
}
