export class UserModel {
  constructor(
    public id: string,
    public name: string,
    public lastname: string,
    public email: string,
    public password: string,
    public img: string,
    public role: string,
    public status: boolean
  ) {}

  public static getInstance(obj: any): UserModel {
    return new UserModel(
      obj.id || obj._id,
      obj.name,
      obj.lastname,
      obj.email,
      obj.password,
      obj.img,
      obj.role,
      obj.status
    );
  }

  edit(obj: any): void {
    this.id = obj.id || this.id;
    this.name = obj.name || this.name;
    this.lastname = obj.lastname || this.lastname;
    this.email = obj.email || this.email;
    this.password = obj.password || this.password;
    this.img = obj.img || this.img;
    this.role = obj.role || this.role;
    this.status = obj.status;
  }
}

export interface ResponseLogin {
  status: boolean;
  user: UserModel;
  token: string;
}

// Generated by https://quicktype.io

export interface ResponseValidSesion {
  status: boolean;
  data: SessionData;
  msg: string;
}

export interface SessionData {
  user: UserModel;
  iat: number;
  exp: number;
}
